name: mpw_precheck

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['gds']
    types: [completed]

jobs:
  generate_fill:
    runs-on: ubuntu-24.04
    env:
      PDK_ROOT: ${{ github.workspace }}/pdk
      PDK: ihp-sg13g2
      MAGIC_RC: ${{ github.workspace }}/pdk/ihp-sg13g2/libs.tech/magic/ihp-sg13g2.magicrc
      MAGIC_VERSION: 8.3.522
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout IHP PDK
        uses: actions/checkout@v4
        with:
          repository: TinyTapeout/IHP-Open-PDK
          path: ${{ env.PDK_ROOT }}
          ref: tt2025
          submodules: recursive

      - name: Install magic VLSI
        run: |
          sudo apt-get install -y m4 python3 libx11-dev tcl-dev tk-dev libcairo2-dev mesa-common-dev libglu1-mesa-dev
          git clone -b ${MAGIC_VERSION} https://github.com/RTimothyEdwards/magic magic
          cd magic
          ./configure
          make -j4 
          sudo make install

      - name: Download artifact (run id = 13973597894)
        uses: dawidd6/action-download-artifact@v6
        id: download_artifact
        with:
          workflow: gds.yaml
          run_id: 13973597894
          workflow_conclusion: success
          name: ihp_submission
          path: tinytapeout-submission

      - name: GDSII -> .mag
        working-directory: tinytapeout-submission/gds
        run: |
          magic -noconsole -dnull -rcfile $MAGIC_RC << EOF
          gds readonly true
          gds rescale false
          gds read tt_ihp_wrapper.gds
          writeall force tt_ihp_wrapper
          writeall modified
          EOF

      - name: Generate fill
        working-directory: tinytapeout-submission/gds
        env:
          FILL_SCRIPT: '${{ env.PDK_ROOT }}/${{ env.PDK }}/libs.tech/magic/generate_fill.py'
        run: |
          # Patch the fill script to use the correct PDK path
          sed -i "s|/\$PDK_PATH|$PDK_ROOT/$PDK|g" $FILL_SCRIPT
          python3 $FILL_SCRIPT -dist -keep tt_ihp_wrapper.mag

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gds_fill
          path: tinytapeout-submission/gds

  mpw_precheck:
    env:
      PYTHONIOENCODING: utf-8
      TO_REPO_ROOT: ${{ github.workspace }}/TO_Repo
      PDK_ROOT: ${{ github.workspace }}/pdk
      PDK: ihp-sg13g2

    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout IHP PDK
        uses: actions/checkout@v4
        with:
          repository: TinyTapeout/IHP-Open-PDK
          path: ${{ env.PDK_ROOT }}
          ref: tt2025
          submodules: recursive

      - name: Checkout TO repo
        uses: actions/checkout@v4
        with:
          repository: IHP-GmbH/TO_Apr2025
          path: ${{ env.TO_REPO_ROOT }}

      - name: Install KLayout
        shell: bash
        run: |
          wget https://github.com/TinyTapeout/klayout/releases/download/v0.29.11/klayout_0.29.11-1_amd64.deb
          sudo apt-get update && sudo apt-get install -y ./klayout_0.29.11-1_amd64.deb

      - name: Download artifact (run id = ${{ github.event.workflow_run.id }})
        uses: dawidd6/action-download-artifact@v6
        id: download_artifact
        with:
          workflow: gds.yaml
          run_id: ${{ github.event.workflow_run.id }}
          workflow_conclusion: success
          name: ihp_submission
          path: tinytapeout-submission

      - name: Run DRC check
        working-directory: tinytapeout-submission
        run: |
          klayout -b -r ${{ env.TO_REPO_ROOT }}/drc/drc.lydrc -rd "in_gds"="gds/tt_ihp_wrapper.gds" -rd "report_file"="tt_ihp_wrapper.gds.lyrdb" 2>&1 | tee tt_ihp_wrapper.gds.log
          if [ $? -ne 0 ]; then
            echo "❌ DRC check failed" | tee -a $GITHUB_STEP_SUMMARY
            exit 1
          fi

          if [ ! -f "tt_ihp_wrapper.gds.lyrdb" ]; then
            echo "❌ DRC report file not found" | tee -a $GITHUB_STEP_SUMMARY
            exit 1
          fi

          if ! grep -q "Number of DRC errors: 0" tt_ihp_wrapper.gds.log; then
            echo "## ❌ DRC errors found in the design" | tee -a $GITHUB_STEP_SUMMARY
            grep "Number of DRC errors:" tt_ihp_wrapper.gds.log | tee -a $GITHUB_STEP_SUMMARY
            exit 1
          fi

          echo "✅ DRC check passed" | tee -a $GITHUB_STEP_SUMMARY

      - name: Upload precheck results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: precheck_results
          path: |
            tinytapeout-submission/tt_ihp_wrapper.gds.lyrdb
            tinytapeout-submission/tt_ihp_wrapper.gds.log
